from __future__ import annotations

STRATEGIES = {
    "long call": {
        "summary": "Bullish, defined-risk call purchase.",
        "setup": "Buy a call at a chosen strike and expiration.",
        "payoff": "Upside increases above the strike; downside limited to premium.",
        "max_profit": "Unlimited upside.",
        "max_loss": "Premium paid.",
        "breakevens": "Strike + premium.",
        "key_sensitivities": "Positive delta and gamma; negative theta; positive vega.",
        "typical_use_case": "Bullish directional view with defined risk.",
        "main_risks": "Time decay and lack of upside move.",
    },
    "long put": {
        "summary": "Bearish, defined-risk put purchase.",
        "setup": "Buy a put at a chosen strike and expiration.",
        "payoff": "Profit increases as price falls below the strike.",
        "max_profit": "Large but capped by stock going to zero.",
        "max_loss": "Premium paid.",
        "breakevens": "Strike - premium.",
        "key_sensitivities": "Negative delta; positive gamma; negative theta; positive vega.",
        "typical_use_case": "Bearish view or crash hedge.",
        "main_risks": "Time decay and lack of downside move.",
    },
    "covered call": {
        "summary": "Income-oriented strategy combining stock and a short call.",
        "setup": "Buy/hold 100 shares and sell 1 call against them.",
        "payoff": "Upside capped at call strike; downside like stock minus premium.",
        "max_profit": "(Call strike - stock cost) + premium.",
        "max_loss": "Large if stock falls; reduced by premium.",
        "breakevens": "Stock cost - premium.",
        "key_sensitivities": "Reduced delta vs long stock; short gamma; short vega.",
        "typical_use_case": "Mildly bullish/neutral income.",
        "main_risks": "Opportunity cost if stock rallies; downside if stock drops.",
    },
    "cash-secured put": {
        "summary": "Income strategy selling a put while holding cash to buy shares.",
        "setup": "Sell a put and set aside cash for potential assignment.",
        "payoff": "Profit up to premium; downside like buying shares below strike.",
        "max_profit": "Premium received.",
        "max_loss": "Large if stock falls to zero; reduced by premium.",
        "breakevens": "Strike - premium.",
        "key_sensitivities": "Positive theta; negative gamma; short vega.",
        "typical_use_case": "Willing to buy at lower effective price.",
        "main_risks": "Downside if stock drops sharply.",
    },
    "bull call spread": {
        "summary": "Bullish, defined-risk vertical using calls.",
        "setup": "Buy a lower-strike call and sell a higher-strike call.",
        "payoff": "Profit rises between strikes, capped above short strike.",
        "max_profit": "Strike width - net debit.",
        "max_loss": "Net debit.",
        "breakevens": "Lower strike + net debit.",
        "key_sensitivities": "Positive delta; limited gamma; reduced vega.",
        "typical_use_case": "Moderately bullish view with capped cost.",
        "main_risks": "Insufficient upside before expiration.",
    },
    "bear call spread": {
        "summary": "Bearish/neutral, defined-risk vertical using calls.",
        "setup": "Sell a lower-strike call and buy a higher-strike call.",
        "payoff": "Profit from premium if price stays below short strike.",
        "max_profit": "Net credit.",
        "max_loss": "Strike width - net credit.",
        "breakevens": "Lower strike + net credit.",
        "key_sensitivities": "Negative delta; positive theta; short vega.",
        "typical_use_case": "Neutral to mildly bearish view.",
        "main_risks": "Rally above short strike.",
    },
    "bull put spread": {
        "summary": "Bullish/neutral, defined-risk vertical using puts.",
        "setup": "Sell a higher-strike put and buy a lower-strike put.",
        "payoff": "Profit from premium if price stays above short strike.",
        "max_profit": "Net credit.",
        "max_loss": "Strike width - net credit.",
        "breakevens": "Higher strike - net credit.",
        "key_sensitivities": "Positive delta; positive theta; short vega.",
        "typical_use_case": "Neutral to mildly bullish view.",
        "main_risks": "Sharp downside move.",
    },
    "bear put spread": {
        "summary": "Bearish, defined-risk vertical using puts.",
        "setup": "Buy a higher-strike put and sell a lower-strike put.",
        "payoff": "Profit rises as price falls, capped below lower strike.",
        "max_profit": "Strike width - net debit.",
        "max_loss": "Net debit.",
        "breakevens": "Higher strike - net debit.",
        "key_sensitivities": "Negative delta; limited gamma; reduced vega.",
        "typical_use_case": "Moderately bearish view.",
        "main_risks": "Insufficient downside move.",
    },
    "long straddle": {
        "summary": "Volatility-seeking long call + long put at same strike.",
        "setup": "Buy a call and a put at the same strike and expiration.",
        "payoff": "Profit from large moves in either direction.",
        "max_profit": "Unlimited upside; large downside potential if stock drops.",
        "max_loss": "Total premium paid.",
        "breakevens": "Strike +/- total premium.",
        "key_sensitivities": "Long gamma and vega; short theta.",
        "typical_use_case": "Expecting big move or volatility increase.",
        "main_risks": "Time decay if price stays near strike.",
    },
    "long strangle": {
        "summary": "Volatility-seeking long call + long put at different strikes.",
        "setup": "Buy OTM call and OTM put with same expiration.",
        "payoff": "Profit from large moves beyond either strike.",
        "max_profit": "Unlimited upside; large downside potential if stock drops.",
        "max_loss": "Total premium paid.",
        "breakevens": "Call strike + total premium; Put strike - total premium.",
        "key_sensitivities": "Long gamma and vega; short theta.",
        "typical_use_case": "Expecting big move but cheaper than straddle.",
        "main_risks": "Time decay; need larger move.",
    },
    "short straddle": {
        "summary": "Income strategy selling call + put at same strike.",
        "setup": "Sell a call and a put at the same strike and expiration.",
        "payoff": "Profit if price stays near strike; large losses if it moves.",
        "max_profit": "Total premium received.",
        "max_loss": "Unlimited on upside; large on downside.",
        "breakevens": "Strike +/- total premium.",
        "key_sensitivities": "Short gamma and vega; long theta.",
        "typical_use_case": "Expecting low volatility.",
        "main_risks": "Large move in either direction.",
    },
    "short strangle": {
        "summary": "Income strategy selling OTM call + OTM put.",
        "setup": "Sell OTM call and OTM put with same expiration.",
        "payoff": "Profit if price stays between strikes.",
        "max_profit": "Total premium received.",
        "max_loss": "Unlimited on upside; large on downside.",
        "breakevens": "Call strike + premium; Put strike - premium.",
        "key_sensitivities": "Short gamma and vega; long theta.",
        "typical_use_case": "Expecting range-bound price.",
        "main_risks": "Large move beyond strikes.",
    },
    "iron condor": {
        "summary": "Defined-risk income strategy using call and put spreads.",
        "setup": "Sell OTM put spread and sell OTM call spread.",
        "payoff": "Profit if price stays between short strikes.",
        "max_profit": "Net credit.",
        "max_loss": "Wings width - net credit.",
        "breakevens": "Short put strike - credit; short call strike + credit.",
        "key_sensitivities": "Short gamma and vega; long theta.",
        "typical_use_case": "Neutral view with defined risk.",
        "main_risks": "Strong move outside range.",
    },
    "iron butterfly": {
        "summary": "Defined-risk income strategy centered at a single strike.",
        "setup": "Sell ATM call and put, buy OTM wings for protection.",
        "payoff": "Max profit near center strike; losses beyond wings.",
        "max_profit": "Net credit.",
        "max_loss": "Wing width - net credit.",
        "breakevens": "Center strike +/- net credit.",
        "key_sensitivities": "Short gamma; long theta; short vega.",
        "typical_use_case": "Expecting low movement around a level.",
        "main_risks": "Move away from center.",
    },
    "collar": {
        "summary": "Protective structure combining stock, long put, and short call.",
        "setup": "Own stock, buy put, sell call.",
        "payoff": "Downside limited by put; upside capped by call.",
        "max_profit": "Capped at call strike minus stock cost plus net credit/debit.",
        "max_loss": "Limited by put strike minus stock cost plus net credit/debit.",
        "breakevens": "Stock cost - net credit (or + net debit).",
        "key_sensitivities": "Reduced delta; limited vega.",
        "typical_use_case": "Hedge existing stock position.",
        "main_risks": "Opportunity cost if stock rallies.",
    },
    "protective put": {
        "summary": "Downside hedge for long stock.",
        "setup": "Own stock and buy a put.",
        "payoff": "Downside limited below put strike; upside preserved minus premium.",
        "max_profit": "Unlimited (stock upside) minus put premium.",
        "max_loss": "Limited to stock cost minus put strike plus premium.",
        "breakevens": "Stock cost + premium.",
        "key_sensitivities": "Long delta with insurance; long vega.",
        "typical_use_case": "Hedging a long stock position.",
        "main_risks": "Cost of insurance if stock rises.",
    },
    "calendar spread": {
        "summary": "Time-decay strategy using different expirations at same strike.",
        "setup": "Sell near-term option and buy longer-term option at same strike.",
        "payoff": "Depends on time decay and IV changes; expiration payoff depends on near-term expiration.",
        "max_profit": "Typically around the strike; varies with IV.",
        "max_loss": "Net debit.",
        "breakevens": "Varies; use calculator with premiums.",
        "key_sensitivities": "Long vega; positive theta after front month decay.",
        "typical_use_case": "Neutral view with expectation of stable price and rising IV.",
        "main_risks": "IV crush or large move.",
    },
    "diagonal spread": {
        "summary": "Vertical + calendar hybrid with different strikes and expirations.",
        "setup": "Buy longer-dated option and sell shorter-dated option at different strikes.",
        "payoff": "Depends on strikes, time decay, and IV.",
        "max_profit": "Varies; often capped by short strike in near term.",
        "max_loss": "Net debit.",
        "breakevens": "Varies; use calculator with premiums.",
        "key_sensitivities": "Long vega; mixed delta.",
        "typical_use_case": "Directional bias with time-decay benefit.",
        "main_risks": "Large move vs short strike; IV changes.",
    },
    "ratio spread": {
        "summary": "Unequal number of long and short options at different strikes.",
        "setup": "Buy fewer options and sell more at a different strike.",
        "payoff": "Can be limited on one side and risky on the other.",
        "max_profit": "Depends on structure; can be capped.",
        "max_loss": "Potentially large if unhedged.",
        "breakevens": "Multiple; structure-dependent.",
        "key_sensitivities": "Can flip delta; short gamma risk.",
        "typical_use_case": "Complex directional or income objectives.",
        "main_risks": "Unbounded risk if not defined.",
    },
    "backspread": {
        "summary": "More long options than short, often for large move bets.",
        "setup": "Sell fewer options near the money, buy more further OTM.",
        "payoff": "Limited loss near short strike, benefits from large moves.",
        "max_profit": "Large on big moves.",
        "max_loss": "Limited (structure dependent).",
        "breakevens": "Multiple; depends on premiums.",
        "key_sensitivities": "Long gamma and vega beyond the short strike.",
        "typical_use_case": "Expecting large volatility move.",
        "main_risks": "Loss if price stalls near short strike.",
    },
}

ALIASES = {
    "csp": "cash-secured put",
    "cash secured put": "cash-secured put",
    "bull call": "bull call spread",
    "bear call": "bear call spread",
    "bull put": "bull put spread",
    "bear put": "bear put spread",
}


def normalize_strategy_name(name: str) -> str:
    key = name.strip().lower()
    return ALIASES.get(key, key)


def get_strategy(name: str):
    key = normalize_strategy_name(name)
    return STRATEGIES.get(key)
